### PR TITLE
Update to Freedesktop runtime 20.08

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by wjt** [comment]
bot, build

**Comment by wjt** [comment]
```
/bin/sh ../libtool  --tag=CC   --mode=link gcc -Wall -g -DCOMMON_DATA_PREFIX=\"/app/share/t4k_common\" -DDEBUG -DUSE_T4K_PREFIX=1  -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection  -I/app/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT   -I/app/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -pthread -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1  -I/app/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -I/usr/include/librsvg-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gdk-pixbuf-2.0 -pthread -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz  -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz  -I/usr/include/libpng16  -I/usr/include/libxml2   -L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed  -o libt4k_common.la -rpath /app/lib t4k_audio.lo t4k_convert_utf.lo t4k_linewrap.lo t4k_loaders.lo t4k_main.lo t4k_menu.lo t4k_pixels.lo t4k_sdl.lo t4k_throttle.lo t4k_replacements.lo linebreak/liblinebreak.la -lm  -L/app/lib -Wl,-rpath,/app/lib -lSDL -lpthread  -L/app/lib -lSDL_image -Wl,-rpath,/app/lib -lSDL -lpthread  -L/app/lib -lSDL_mixer -Wl,-rpath,/app/lib -lSDL -lpthread  -L/app/lib -lSDL_Pango -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz  -L/app/lib -lSDL_net -Wl,-rpath,/app/lib -lSDL -lpthread  -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo  -lcairo  -lpng16 -lz  -lxml2 
libtool: link: gcc -shared  -fPIC -DPIC  .libs/t4k_audio.o .libs/t4k_convert_utf.o .libs/t4k_linewrap.o .libs/t4k_loaders.o .libs/t4k_main.o .libs/t4k_menu.o .libs/t4k_pixels.o .libs/t4k_sdl.o .libs/t4k_throttle.o .libs/t4k_replacements.o  -Wl,--whole-archive linebreak/.libs/liblinebreak.a -Wl,--no-whole-archive  -Wl,-rpath -Wl,/app/lib -Wl,-rpath -Wl,/app/lib -L/app/lib /app/lib/libSDL_image.so /app/lib/libSDL_mixer.so /app/lib/libSDL_Pango.so -lpangoft2-1.0 -lfontconfig -lfreetype -lpango-1.0 -lharfbuzz /app/lib/libSDL_net.so /app/lib/libSDL.so -ldl -lpthread -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo -lpng16 -lz -lxml2  -g -O2 -g -fstack-protector-strong -grecord-gcc-switches -pthread -pthread -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,--as-needed -Wl,-rpath -Wl,/app/lib -Wl,-rpath -Wl,/app/lib -Wl,-rpath -Wl,/app/lib -Wl,-rpath -Wl,/app/lib   -pthread -Wl,-soname -Wl,libt4k_common.so.0 -o .libs/libt4k_common.so.0.0.0
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: .libs/t4k_convert_utf.o:/run/build/t4kcommon/src/t4k_common.h:242: multiple definition of `wrapped_lines'; .libs/t4k_audio.o:/run/build/t4kcommon/src/t4k_common.h:242: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: .libs/t4k_linewrap.o:/run/build/t4kcommon/src/t4k_common.h:242: multiple definition of `wrapped_lines'; .libs/t4k_audio.o:/run/build/t4kcommon/src/t4k_common.h:242: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: .libs/t4k_loaders.o:/run/build/t4kcommon/src/t4k_common.h:242: multiple definition of `wrapped_lines'; .libs/t4k_audio.o:/run/build/t4kcommon/src/t4k_common.h:242: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: .libs/t4k_main.o:/run/build/t4kcommon/src/t4k_common.h:242: multiple definition of `wrapped_lines'; .libs/t4k_audio.o:/run/build/t4kcommon/src/t4k_common.h:242: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: .libs/t4k_menu.o:/run/build/t4kcommon/src/t4k_common.h:242: multiple definition of `wrapped_lines'; .libs/t4k_audio.o:/run/build/t4kcommon/src/t4k_common.h:242: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: .libs/t4k_pixels.o:/run/build/t4kcommon/src/t4k_common.h:242: multiple definition of `wrapped_lines'; .libs/t4k_audio.o:/run/build/t4kcommon/src/t4k_common.h:242: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: .libs/t4k_sdl.o:/run/build/t4kcommon/src/t4k_common.h:242: multiple definition of `wrapped_lines'; .libs/t4k_audio.o:/run/build/t4kcommon/src/t4k_common.h:242: first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: .libs/t4k_throttle.o:/run/build/t4kcommon/src/t4k_common.h:242: multiple definition of `wrapped_lines'; .libs/t4k_audio.o:/run/build/t4kcommon/src/t4k_common.h:242: first defined here
collect2: error: ld returned 1 exit status
```

**Comment by wjt** [comment]
bot, build 🤖🤖

**Comment by wjt** [comment]
Made a start on some upstream fixes for the errors the new toolchain is rightly complaining about.

**Comment by akurtakov** [comment]
I give up on this one as 21.08 is out and one would better go to it directly.

**Pull request closed without merging**
